- name: Capture command output
  hosts: db_servers
  become: true
  tasks:
    - name: Capture command output
      command: cat /path/to/file.txt
      register: file_output

    - name: Print command output
      debug:
        var: file_output.stdout

