- name: Copy file with permissions
  hosts: db_servers
  become: true
  tasks:
    - name: Copy file with permissions
      copy:
        src: /path/to/local/file.txt
        dest: /path/on/remote/file.txt
        mode: '0644'
        owner: dbadmin
        group: dbgroup

