- name: Wait for condition
  hosts: all
  become: true
  tasks:
    - name: Wait for condition
      wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: 22
        state: stopped
        delay: 10
        timeout: 300

