- name: Execute command with arguments
  hosts: app_servers
  become: true
  tasks:
    - name: Execute command with arguments
      shell: echo "Welcome, {{ username }}!"
      vars:
        username: "John"

