- name: Update INI file
  hosts: all
  become: true
  tasks:
    - name: Add or update option
      ini_file:
        path: /etc/myapp.conf
        section: mysection
        option: myoption
        value: myvalue

