- name: Download file with checksum validation
  hosts: all
  become: true
  tasks:
    - name: Download file
      get_url:
        url: http://example.com/file.tar.gz
        dest: /tmp/file.tar.gz
        checksum: sha256:7d7f28f1bfe6...
        mode: '0644'

